[tool.portray]
modules = ["dcm2bids"]
# docs_dir = ["docs"]
# extra_dirs = ["media", "art"]

# Set plugins
[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions.toc]
    permalink = "⚓︎"

[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions."pymdownx.highlight"]
    linenums = true

[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions."pymdownx.tasklist"]
    custom_checkbox = true
    clickable_checkbox = false

[tool.portray.mkdocs]
# Repository
repo_name = "UNFmontreal/dcm2bids" # Name in top right corner
# Set repo_url so anyone running from their own repo can see from true dcm2bids repo.
repo_url = "https://github.com/UNFmontreal/Dcm2Bids"
edit_uri = "blob/master/" # Bring to the page on GH, but it won't open the _edit_ mode.

# Left navigation menu
nav = [{  Home = "README.md"},
       {  "Code of conduct" = "CODE_OF_CONDUCT.md" },
       {  "Contributing" = "CONTRIBUTING.md"},
       {  "1. Usage" = "docs/1-usage.md"},
       {  "2. Tutorial" = "docs/2-tutorial.md"},
       {  "3. Configuration" = "docs/3-configuration.md"},
       {  "4. Advanced" = "docs/4-advanced.md"},
       {  "Changelog" = "CHANGELOG.md"}]

extra_css = ["docs/stylesheets/extra.css"] # To fix some colors in light vs slate mode.

markdown_extensions = ["admonition",
                       "footnotes",
                       "pymdownx.emoji",
                       "pymdownx.caret",
                       "pymdownx.mark",
                       "pymdownx.tilde",
                       "pymdownx.details",
                       "pymdownx.superfences",
                       "pymdownx.tabbed"]

# Add a bunch of markdown extensions to improve the documentation (and the look ;)).
# See https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
# for full list of extensions.

[tool.portray.mkdocs.theme]
name = "material"
# Blurb that is output when the doc site is shared on social media or elsewhere.
site_description = """
  This is the documentation for dcm2bids, a community-centered project
  that aims to be an easy-to-use tool to automate the process of 1- converting
  DICOM files to NIfTI files with dcm2niix and 2- reorganising NIfTI files into the Brain
  Imaging Data Structure (BIDS).
  """

[[tool.portray.mkdocs.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"

  [tool.portray.mkdocs.theme.palette.toggle]
  icon = "material/toggle-switch-off-outline"
  name = "Switch to dark mode"

[[tool.portray.mkdocs.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"

  [tool.portray.mkdocs.theme.palette.toggle]
  icon = "material/toggle-switch"
  name = "Switch to light mode"

[[tool.portray.mkdocs.plugins]]
[tool.portray.mkdocs.plugins.search]

[[tool.portray.mkdocs.plugins]]
[tool.portray.mkdocs.plugins.git-revision-date-localized]
type = "timeago"
enable_creation_date = true
fallback_to_build_date = true

icon = {repo = "fontawesome/brands/github"} # icon in top-right corner.

# TODO: Design a logo and/or favicon.
# favicon = "art/logo_small.png"
# logo = "art/logo_small.png"

## Footer icon in bottom-right corner
[[tool.portray.mkdocs.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/UNFmontreal/Dcm2Bids"
name = "dcm2bids on GitHub"

[[tool.portray.mkdocs.extra.social]]
icon = "fontawesome/brands/docker"
link = "https://hub.docker.com/r/unfmontreal/dcm2bids"
name = "dcm2bids on docker"
